# Generated by Django 5.1.4 on 2026-08-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('serving_size', models.CharField(default='100g', max_length=50)),
                ('calories', models.PositiveIntegerField(help_text='kcal per serving')),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='snack', max_length=20)),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('date', models.DateField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Meal entries',
                'ordering': ['-date', '-logged_at'],
            },
        ),
    ]
